baseURL: http://www.example.com
title: Home
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Adrian Pascual
  avatarURL: images/avatar.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Adrian's personal website
  hideColorSchemeToggle: no
  info:
    - Data Analyst
  keywords: blog,data analyst,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2019
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/adrian-pascual
      weight: 1
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/adrian-pascual/
      weight: 2
    - icon: fa fa-2x fa-bar-chart
      name: Tableau
      url: https://public.tableau.com/app/profile/apascual#!/
      weight: 3
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: dracula